# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-24 09:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamwork_record', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='outcome',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='outcome',
            name='during',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='outcome',
            name='project',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='outcome',
            name='total',
            field=models.TextField(null=True),
        ),
    ]
