# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-25 06:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamwork_record', '0002_auto_20180124_0904'),
    ]

    operations = [
        migrations.AddField(
            model_name='outcome',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='outcome',
            name='start_time',
            field=models.DateTimeField(null=True),
        ),
    ]
