# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-25 07:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamwork_record', '0003_auto_20180125_0649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outcome',
            name='end_time',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='outcome',
            name='start_time',
            field=models.TextField(null=True),
        ),
    ]
