# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-26 14:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamwork_record', '0005_outcome_generate_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outcome',
            name='end_time',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='outcome',
            name='start_time',
            field=models.DateField(null=True),
        ),
    ]
