# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-26 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamwork_record', '0006_auto_20180126_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outcome',
            name='during',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='outcome',
            name='total',
            field=models.IntegerField(null=True),
        ),
    ]
